name: Build project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate build files
      run: cmake -B build
    - name: Build project
      run: cmake --build build --target EUtilities
