name: Create release
on:
  push:
    tags:
      - v*.*
jobs:
  build:
    name: Build project and create release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate build files
        run: cmake -B build
      - name: Build project Debug
        run: cmake --build build --target EUtilities --config Debug
      - name: Build project Release
        run: cmake --build build --target EUtilities --config Release
      - name: Where are my files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/Debug/EUtilities-Debug.lib
            build/Release/EUtilities.lib