name: Create release
on:
  push:
    tags:
      - v*.*

jobs:
  build:
    name: Build project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Generate build files
      - name: Generate build files
        run: cmake -B build

      # Build Debug
      - name: Build project Debug
        run: cmake --build build --target EUtilities --config Debug

      # Build Release
      - name: Build project Release
        run: cmake --build build --target EUtilities --config Release

      # # Upload artifacts
      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: eutilities-libs
      #     path: |
      #       build/Debug/EUtilities.lib
      #       build/Release/EUtilities.lib

  release:
    name: Create release
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # # Download artifacts from the build job
      # - name: Download build artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: eutilities-libs

      - name: Where are my files
        run: ls -R
      # Create the release and upload artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Debug/EUtilities.lib
            Release/EUtilities.lib